# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import register_activate.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('salt', models.CharField(default=register_activate.forms.make_salt, max_length=10)),
                ('activation_request_date', models.DateTimeField(auto_now_add=True)),
                ('activated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
